# Generated by Django 5.2.12 on 2026-04-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo_hex', models.CharField(default='#000000', help_text='Código hexadecimal, ej: #1e3a5f', max_length=7)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Mi Tienda de Ropa', max_length=100)),
                ('slogan', models.CharField(default='Moda para todos los estilos', max_length=200)),
                ('descripcion_hero', models.TextField(default='Encontrá las mejores camperas, remeras, buzos y pantalones.', help_text='Texto que aparece debajo del título en el carrusel principal.')),
                ('telefono', models.CharField(default='+54 9 11 0000-0000', max_length=30)),
                ('whatsapp', models.CharField(default='+5491100000000', help_text='Número con código de país, sin espacios ni guiones.', max_length=30)),
                ('email', models.EmailField(default='tienda@ejemplo.com', max_length=254)),
                ('direccion', models.CharField(default='Buenos Aires, Argentina', max_length=200)),
                ('horario_atencion', models.CharField(default='Lunes a Viernes 9:00 - 18:00', max_length=200)),
                ('info_envio', models.TextField(default='Enviamos por correo a todo el país. El costo de envío corre por cuenta del cliente. También podés coordinar retiro en punto acordado con el vendedor.', help_text='Texto informativo sobre envíos que aparece en el sitio.')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com/')),
                ('tiktok', models.URLField(blank=True, default='')),
                ('titulo_ofertas', models.CharField(default='Ofertas de la Semana', max_length=100)),
                ('descripcion_ofertas', models.TextField(blank=True, default='Aprovechá nuestros descuentos especiales en prendas seleccionadas.')),
                ('texto_footer', models.CharField(default='© 2025 Mi Tienda de Ropa. Todos los derechos reservados.', max_length=300)),
                ('mp_public_key', models.CharField(blank=True, default='', help_text='Public Key de MercadoPago (TEST o PROD).', max_length=200)),
                ('mp_access_token', models.CharField(blank=True, default='', help_text='Access Token de MercadoPago (TEST o PROD).', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='carrusel/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=150, verbose_name='Título (opcional)')),
                ('subtitulo', models.CharField(blank=True, max_length=250, verbose_name='Subtítulo (opcional)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Imágenes del Carrusel',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('tipo_entrega', models.CharField(choices=[('correo', 'Envío por correo'), ('acordado', 'Retiro en punto acordado')], default='correo', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del cliente.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mp_preference_id', models.CharField(blank=True, max_length=200)),
                ('mp_payment_id', models.CharField(blank=True, max_length=200)),
                ('mp_status', models.CharField(blank=True, max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('visible', models.BooleanField(default=False, help_text='Marcar para mostrar públicamente en la página principal.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sugerencia / Testimonio',
                'verbose_name_plural': 'Sugerencias / Testimonios',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: S, M, L, XL, 2XL, 3XL', max_length=10, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Talle',
                'verbose_name_plural': 'Talles',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Si tiene precio de oferta, ingresalo aquí.', max_digits=10, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('destacado', models.BooleanField(default=False, help_text='Aparece en la sección de destacados.')),
                ('en_oferta', models.BooleanField(default=False, help_text='Aparece en la sección de ofertas.')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tienda.categoria')),
                ('colores_disponibles', models.ManyToManyField(blank=True, related_name='productos', to='tienda.color')),
                ('talles_disponibles', models.ManyToManyField(blank=True, related_name='productos', to='tienda.talle')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('talle', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Ítem del Pedido',
                'verbose_name_plural': 'Ítems del Pedido',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, help_text='Asociá esta imagen a un color específico (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen del Producto',
                'verbose_name_plural': 'Imágenes del Producto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='VarianteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='tienda.producto')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.talle')),
            ],
            options={
                'verbose_name': 'Variante de Stock',
                'verbose_name_plural': 'Variantes de Stock',
                'unique_together': {('producto', 'talle', 'color')},
            },
        ),
    ]
